Fix: Include allowedVendor param and update ModuleId value
mparticle-integrations/mparticle-javascript-integration-id5 pull request #13
Opened 2024-12-11 14:59 UTC by gh-mmurph

## Summary
Added new consent param to ID5 init per their recommendation and updated the ModuleId value as it looked to make ID5 kit initialization fail in my end to end test; this may be just impacting me but using a number ensure it matches how other kits are set-up.

## Testing Plan
{explain how this has been tested, and what additional testing should be done}

## Master Issue
Closes https://go.mparticle.com/work/REPLACE

2024-12-16 16:07 UTC, shwangMP approved these changes

2024-12-18 14:40 UTC, alexs-mparticle requested changes

2024-12-18 14:40 UTC, alexs-mparticle commented on dist/ID5Kit.common.js
> +        var id5Instance = window.ID5.init({
Please don't check in the `/dist` folder in your PRs. These files are built when we release and any merge conflicts will prevent us from using automated releases.

2024-12-18 14:40 UTC, alexs-mparticle commented on src/identity-handler.js
> +                allowedVendors: [ '131', 'ID5-1747' ]
I see you're repeating some of these string values and there's a _slight_ risk of some typos. I would make these values into constants so they can be reused and give us some safety.

2024-12-18 18:48 UTC, closed without merging