feat: initialize ID5 SDK and access/store the ID5 ID
mparticle-integrations/mparticle-javascript-integration-id5 pull request #2
Opened 2024-08-07 17:55 UTC by SbDove

## Summary
{provide a thorough description of the changes}
This PR adds the code to initialize the ID5 SDK and accesses/assigns the ID5 ID. 

## Testing Plan
{explain how this has been tested, and what additional testing should be done}
Tested locally and unit tests to cover the code have been added. 

## Master Issue
Closes https://mparticle-eng.atlassian.net/browse/SQDPB-4025

2024-10-08 14:28 UTC, alexs-mparticle requested changes

2024-10-08 14:28 UTC, alexs-mparticle commented on src/common.js
> +    debugger;
```suggestion
```

2024-10-08 14:28 UTC, alexs-mparticle commented on src/common.js
> +    if (id5Id != this.id5Id) {
```suggestion
    if (id5Id !== this.id5Id) {
```

2024-10-08 14:28 UTC, alexs-mparticle commented on src/common.js
> +    if (this.id5IdSent == false){
```suggestion
    if (this.id5IdSent === false){
```

2024-10-08 14:28 UTC, alexs-mparticle commented on src/common.js
> +}.bind(this);
Why are you adding `bind(this)` here?

2024-10-08 14:28 UTC, alexs-mparticle commented on src/common.js
> +    }
If this variable isn't being used anywhere else, I think you can just directly assign.

```suggestion
    if (email) {
        pdKeys[1] = SHA256(this.normalizeEmail(email));
    }
```

2024-10-08 14:28 UTC, alexs-mparticle commented on src/common.js
> +    }
Same here

```suggestion
    if (phone) {
        pdKeys[2] = SHA256(this.normalizePhone(phone));
    }
```

2024-10-08 14:28 UTC, alexs-mparticle commented on src/event-handler.js
> +};
Formatting Nit.

```suggestion
EventHandler.prototype.logEvent = function() {};
```

2024-10-08 16:38 UTC, SbDove commented on src/common.js
> +}.bind(this);
I added it while testing out of confusion and missed removing it afterwords. its been removed

2024-10-08 16:38 UTC, SbDove commented on src/common.js
> +    }
updated

2024-10-08 20:39 UTC, alexs-mparticle requested changes

2024-10-08 20:39 UTC, alexs-mparticle commented on src/event-handler.js
> +
```suggestion
```

2024-10-08 20:39 UTC, alexs-mparticle commented on src/initialization.js
> +            var id5Script = document.createElement('script');
Can you include any links to their documentation, specifically their initialization? It would be helpful in case we need it for the future.

2024-10-08 20:39 UTC, alexs-mparticle commented on src/common.js
> +    var pdRaw = Object.keys(pdKeys).map(function(key){
What happens if there are no keys in `pdKeys`? I would assume we'd end up passing an empty string into `btoa`, which may be safe. However make sure you have a test for the negative case if possible.

2024-10-08 20:39 UTC, alexs-mparticle commented on src/common.js
> +        parts[0] = parts[0].replaceAll(character, '').toLowerCase();
Be careful with `replaceAll` as it isn't supported by older browsers and may break for some devices, like Smart TVs (speaking from experience).

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#browser_compatibility

2024-10-08 20:39 UTC, alexs-mparticle commented on src/identity-handler.js
> +    mParticleUser
Please provide a comment explaining why we need to re-init ID5 so that we aren't scratching our heads if we have to update this kit.

2024-10-08 20:39 UTC, alexs-mparticle commented on test/src/tests.js
> +            pd.should.equal('MT03MzA2MmQ4NzI5MjZjMmE1NTZmMTdiMzZmNTBlMzI4ZGRmOWJmZjlkNDAzOTM5YmQxNGI2YzNiN2Y1YTMzZmMy')
Is this a real key? I don't think we should be committing this. If at all possible, use (shorter) fake values

2024-10-08 20:39 UTC, alexs-mparticle commented on test/src/tests.js
> +        it ('should normalize phone numbers when normalizePhone is called', function(done) {
We should have negative test cases for these utility methods, such as what if someone passes a string or an incorrect phone number.

2024-10-08 20:39 UTC, alexs-mparticle commented on test/src/tests.js
> +        it ('should normalize an gmail when normalizeEmail is called', function(done) {
We should have negative test cases for these utility methods, such as what if someone passes an incorrect email address.

2024-10-08 20:53 UTC, SbDove commented on test/src/tests.js
> +            pd.should.equal('MT03MzA2MmQ4NzI5MjZjMmE1NTZmMTdiMzZmNTBlMzI4ZGRmOWJmZjlkNDAzOTM5YmQxNGI2YzNiN2Y1YTMzZmMy')
This was btoa output of the fake identities included in the test case, it's not a key. I can either 1. leave a comment explaining that fact or 2. try to find a way to mock the btoa function to return a fake value - what makes the most sense?

2024-10-08 20:58 UTC, alexs-mparticle commented on test/src/tests.js
> +            pd.should.equal('MT03MzA2MmQ4NzI5MjZjMmE1NTZmMTdiMzZmNTBlMzI4ZGRmOWJmZjlkNDAzOTM5YmQxNGI2YzNiN2Y1YTMzZmMy')
My mistake. I would prefer mocking bota as it is a better practice when testing, but if that isn't a viable option, I'm happy with a comment.

2024-10-09 19:33 UTC, SbDove commented on src/common.js
> +    var pdRaw = Object.keys(pdKeys).map(function(key){
Added additional test coverage to account for this situation. I also put a catch to exit the function in cases where there are no keys to assign in the `pdKeys`.

2024-10-10 17:06 UTC, alexs-mparticle approved these changes

2024-10-10 18:21 UTC, merged