feat: store id5 id to integration attributes
mparticle-integrations/mparticle-javascript-integration-id5 pull request #7
Opened 2024-10-24 19:16 UTC by SbDove

## Summary
{provide a thorough description of the changes}
This PR stores the encrypted ID5 ID as an integration attribute for decryption by an inbound rule. 

## Testing Plan
{explain how this has been tested, and what additional testing should be done}
Unit tests were added to cover the changes. 

## Master Issue
Closes https://mparticle-eng.atlassian.net/browse/SQDPB-4026

2024-11-05 20:48 UTC, alexs-mparticle requested changes

2024-11-05 20:48 UTC, alexs-mparticle commented on src/common.js
> +    integrationAttributes['id5IdType'] = this.id5IdType;
Some of these keys like `Id5Id` look like it would be very prone to typos so I would make them constants. However, it might be cleaner to do it this way:

```suggestion
    var integrationAttributes = {
        encryptedId5Id: id5Id,
        id5IdType: this.id5IdType
    };
```

Although I would be curious if there's any issue with either of these values being `null` or `undefined`. If that's the case, I would come up with default values.

2024-11-05 20:48 UTC, alexs-mparticle commented on test/src/tests.js
> +            var attributes = integrationAttributes[248];
It took me a minute to figure out that `248` is the module Id for this kit. I would avoid using the number directly and either reference it via `mParticle.forwarder.initialization.moduleId` or create a constant to reference this value. This may prevent future head scratching.

2024-11-06 18:30 UTC, SbDove commented on src/common.js
> +    integrationAttributes['id5IdType'] = this.id5IdType;
`id5Id` is already checked for null or undefined above in the function. The id5IdType is a required setting for the integration so should always be present.

2024-11-06 18:34 UTC, alexs-mparticle approved these changes

2024-11-06 18:34 UTC, merged